name: Publish to the Ballerina DEV/STAGE Central

on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: Select environment
          required: true
          options:
            - DEV CENTRAL
            - STAGE CENTRAL

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set Up Ballerina
              uses: ballerina-platform/setup-ballerina@v1.1.0
              with:
                version: latest
                
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17.0.7

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Ballerina Central Dev Push
              if: ${{ inputs.environment == 'DEV CENTRAL' }}
              env:
                BALLERINA_DEV_CENTRAL: true
                BALLERINA_STAGE_CENTRAL: false
                BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
              run: |
                sed -i 's/version=\(.*\)-SNAPSHOT/version=\1/g' gradle.properties
                ./gradlew clean build
                ./gradlew :edi-tools-package:publishEDIPackage 
      
            - name: Ballerina Central Stage Push
              if: ${{ inputs.environment == 'STAGE CENTRAL' }}
              env:
                BALLERINA_DEV_CENTRAL: false
                BALLERINA_STAGE_CENTRAL: true
                BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
              run: |
                sed -i 's/version=\(.*\)-SNAPSHOT/version=\1/g' gradle.properties
                ./gradlew clean build
                ./gradlew :edi-tools-package:publishEDIPackage 
